approvedGitRepositories:
  - "**"

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

packageExtensions:
  "@react-types/color@*":
    peerDependenciesMeta:
      "@react-spectrum/provider":
        optional: true
  "@typescript-eslint/project-service@*":
    peerDependenciesMeta:
      typescript:
        optional: true
  "@typescript-eslint/tsconfig-utils@*":
    peerDependenciesMeta:
      typescript:
        optional: true
  "@typescript-eslint/typescript-estree@*":
    peerDependenciesMeta:
      typescript:
        optional: true
  "@typescript-eslint/utils@*":
    peerDependenciesMeta:
      typescript:
        optional: true
  ts-api-utils@*:
    peerDependenciesMeta:
      typescript:
        optional: true
